version: '3.3'
services:
  pgdatabase:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    image: django
    build: .
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/agenda_me
    ports:
      - "8000:8000"
    depends_on:
      - pgdatabase
  
